(* WARNING: This file was generated automatically by Vehicle *)
(* and should not be modified manually! *)
(* Metadata: *)
(*  - Vehicle version: 0.24.1+dev *)
(*  - Rocq version: 9.0.0 *)

From mathcomp Require Import all_boot.
From mathcomp Require Import all_algebra.
From mathcomp Require Import interval_inference.
From mathcomp Require Import all_reals.
From mathcomp Require Import Rstruct.
From vehicle Require Import utils.
Require Import Stdlib.Reals.Reals.
Local Open Scope ring_scope.
Local Open Scope order_scope.
Local Open Scope tensor_scope.

Notation R := Rdefinitions.R.

Definition UnnormalisedInputVector : Type := 'nT[R]_[5].

Definition InputVector : Type := 'nT[R]_[5].

Definition conc : 'I_5%N := 0.

Definition temp : 'I_5%N := 1.

Definition wbc : 'I_5%N := 2.

Definition age : 'I_5%N := 3.

Definition weight : 'I_5%N := 4.

Definition OutputVector : Type := 'nT[R]_[1].

Parameter meanScalingValues : UnnormalisedInputVector.

Parameter standardDeviationValues : UnnormalisedInputVector.

Definition normalise (x : UnnormalisedInputVector) : InputVector := nstack (fun i => (x ^^ i - meanScalingValues ^^ i) / standardDeviationValues ^^ i).

Parameter pk : InputVector -> OutputVector.

Definition normpk (x : UnnormalisedInputVector) : OutputVector := pk (normalise x).

Definition Ka : 'sT[R] := const_t (9 / 2 : R).

Axiom Ka_pos : const_t (0 : R) < Ka.

Definition Ke : 'sT[R] := const_t (7 / 2 : R).

Axiom Ke_pos : const_t (0 : R) < Ke.

Axiom Ke_n_Ka : Ka != Ke.

Definition Vd : 'sT[R] := const_t (10 : R).

Axiom Vd_pos : const_t (0 : R) < Vd.

Definition C_safe : 'sT[R] := const_t (60 : R).

Axiom C_safe_pos : const_t (0 : R) < C_safe.

Definition ttd : 'sT[R] := const_t (2 : R).

Axiom ttd_pos : const_t (0 : R) < ttd.

Definition Ka_over : 'sT[R] := const_t (807 / 2500 : R).

Definition Ka_under : 'sT[R] := const_t (3227 / 10000 : R).

Definition Ke_over : 'sT[R] := const_t (83 / 200 : R).

Definition Ke_under : 'sT[R] := const_t (4149 / 10000 : R).

Definition eps : 'sT[R] := const_t (1 / 1000 : R).

Definition safeFarInput (x : InputVector) : Prop := (const_t (0 : R) <= x ^^ conc /\ x ^^ conc <= C_safe * const_t (99 / 100 : R)) /\ ((const_t (73 / 2 : R) <= x ^^ temp /\ x ^^ temp <= const_t (40 : R)) /\ ((const_t (15 / 2 : R) <= x ^^ wbc /\ x ^^ wbc <= const_t (20 : R)) /\ ((const_t (18 : R) <= x ^^ age /\ x ^^ age <= const_t (89 : R)) /\ (const_t (50 : R) <= x ^^ weight /\ x ^^ weight <= const_t (100 : R))))).

Definition safeFarOutput (x : InputVector) : Prop := let y := ((normpk x) ^^ 0 * Ka) / (Vd * (Ka - Ke)) in if (Ka < Ke) then (x ^^ conc + y * (Ke_under - Ka_over) < C_safe) else (x ^^ conc + y * (Ke_over - Ka_under) < C_safe).

Axiom safeFar : forall x, safeFarInput x -> safeFarOutput x.

Definition safeNearInput (x : InputVector) : Prop := (C_safe * const_t (99 / 100 : R) <= x ^^ conc /\ x ^^ conc <= C_safe) /\ ((const_t (73 / 2 : R) <= x ^^ temp /\ x ^^ temp <= const_t (40 : R)) /\ ((const_t (15 / 2 : R) <= x ^^ wbc /\ x ^^ wbc <= const_t (20 : R)) /\ ((const_t (18 : R) <= x ^^ age /\ x ^^ age <= const_t (89 : R)) /\ (const_t (50 : R) <= x ^^ weight /\ x ^^ weight <= const_t (100 : R))))).

Definition safeNearOutput (x : InputVector) : Prop := (normpk x) ^^ 0 < eps.

Axiom safeNear : forall x, safeNearInput x -> safeNearOutput x.

Definition safeInput (x : InputVector) : Prop := (const_t (0 : R) <= x ^^ conc /\ x ^^ conc <= C_safe) /\ ((const_t (73 / 2 : R) <= x ^^ temp /\ x ^^ temp <= const_t (40 : R)) /\ ((const_t (15 / 2 : R) <= x ^^ wbc /\ x ^^ wbc <= const_t (20 : R)) /\ ((const_t (18 : R) <= x ^^ age /\ x ^^ age <= const_t (89 : R)) /\ (const_t (50 : R) <= x ^^ weight /\ x ^^ weight <= const_t (100 : R))))).

Definition nonNegOutput (x : InputVector) : Prop := const_t (0 : R) <= (normpk x) ^^ 0.

Axiom nonNeg : forall x, safeInput x -> nonNegOutput x.